from collections import namedtuple
arop = ('add', 'or', 'adc', 'sbb', 'and', 'sub', 'xor', 'cmp')
grp1 = ('test', '', 'not', 'neg', 'mul', 'imul', 'div', 'idiv')
grp2 = ('inc', 'dec', '', '', '', '', '', '')
grp3 = ('inc', 'dec', 'call', 'call', 'jmp', 'jmp', 'push', '')
shfop = ( 'rol', 'ror', 'rcl', 'rcr', 'shl', 'shr', '', 'sar')

ArgType = namedtuple('ArgType', 'cls bits literal hasAddrModeByte displacement data')

argImm8 =      ArgType('Imm',     8,  None, False, '',  'B')
argSImm8 =     ArgType('Imm',     8,  None, False, '',  'b')
argImm16 =     ArgType('Imm',     16, None, False, '',  'H')

argMem16 =     ArgType('Mem',     16, None, True,  '',  '' )
argMem32 =     ArgType('Mem',     32, None, True,  '',  '' )
argMem8 =      ArgType('Mem',     8,  None, True,  '',  '' )

argReg8 =      ArgType('Reg',     8,  None, True,  '',  '' )
argReg16 =     ArgType('Reg',     16, None, True,  '',  '' )
argSegReg =    ArgType('Reg',  'seg', None, True,  '',  '' )

argRegMem8 =   ArgType('RegMem',  8,  None, True,  '',  '' )
argRegMem16 =  ArgType('RegMem',  16, None, True,  '',  '' )

argFar =       ArgType('Far',     32, None, False, 'I', '' )
argNear =      ArgType('Near',    16, None, False, 'h', '' )
argShort =     ArgType('Short',   8,  None, False, 'b', '' )
argMemOffs16 = ArgType('MemOffs', 16, None, False, 'h', '' )
argMemOffs8 =  ArgType('MemOffs', 8,  None, False, 'h', '' )

argNone =      ArgType('None',  None, '',   False, '',  '' )
reg = lambda x: ArgType('Reg',  None, x,    False, '',  '' )
const = lambda x: ArgType('Const', None, str(x), False, '', '')

optable = (
    ('add'   , argRegMem8  , argReg8     , False),
    ('add'   , argRegMem16 , argReg16    , False),
    ('add'   , argReg8     , argRegMem8  , False),
    ('add'   , argReg16    , argRegMem16 , False),
    ('add'   , reg('al')   , argImm8     , False),
    ('add'   , reg('ax')   , argImm16    , False),
    ('push'  , reg('es')   , argNone     , False),
    ('pop'   , reg('es')   , argNone     , False),
    ('or'    , argRegMem8  , argReg8     , False),
    ('or'    , argRegMem16 , argReg16    , False),
    ('or'    , argReg8     , argRegMem8  , False),
    ('or'    , argReg16    , argRegMem16 , False),
    ('or'    , reg('al')   , argImm8     , False),
    ('or'    , reg('ax')   , argImm16    , False),
    ('push'  , reg('cs')   , argNone     , False),
    (''      , argNone     , argNone     , False),
    ('adc'   , argRegMem8  , argReg8     , False),
    ('adc'   , argRegMem16 , argReg16    , False),
    ('adc'   , argReg8     , argRegMem8  , False),
    ('adc'   , argReg16    , argRegMem16 , False),
    ('adc'   , reg('al')   , argImm8     , False),
    ('adc'   , reg('ax')   , argImm16    , False),
    ('push'  , reg('ss')   , argNone     , False),
    ('pop'   , reg('ss')   , argNone     , False),
    ('sbb'   , argRegMem8  , argReg8     , False),
    ('sbb'   , argRegMem16 , argReg16    , False),
    ('sbb'   , argReg8     , argRegMem8  , False),
    ('sbb'   , argReg16    , argRegMem16 , False),
    ('sbb'   , reg('al')   , argImm8     , False),
    ('sbb'   , reg('ax')   , argImm16    , False),
    ('push'  , reg('ds')   , argNone     , False),
    ('pop'   , reg('ds')   , argNone     , False),
    ('and'   , argRegMem8  , argReg8     , False),
    ('and'   , argRegMem16 , argReg16    , False),
    ('and'   , argReg8     , argRegMem8  , False),
    ('and'   , argReg16    , argRegMem16 , False),
    ('and'   , reg('al')   , argImm8     , False),
    ('and'   , reg('ax')   , argImm16    , False),
    ('seges' , argNone     , argNone     , True),
    ('daa'   , argNone     , argNone     , False),
    ('sub'   , argRegMem8  , argReg8     , False),
    ('sub'   , argRegMem16 , argReg16    , False),
    ('sub'   , argReg8     , argRegMem8  , False),
    ('sub'   , argReg16    , argRegMem16 , False),
    ('sub'   , reg('al')   , argImm8     , False),
    ('sub'   , reg('ax')   , argImm16    , False),
    ('segcs' , argNone     , argNone     , True),
    ('das'   , argNone     , argNone     , False),
    ('xor'   , argRegMem8  , argReg8     , False),
    ('xor'   , argRegMem16 , argReg16    , False),
    ('xor'   , argReg8     , argRegMem8  , False),
    ('xor'   , argReg16    , argRegMem16 , False),
    ('xor'   , reg('al')   , argImm8     , False),
    ('xor'   , reg('ax')   , argImm16    , False),
    ('segss' , argNone     , argNone     , True),
    ('aaa'   , argNone     , argNone     , False),
    ('cmp'   , argRegMem8  , argReg8     , False),
    ('cmp'   , argRegMem16 , argReg16    , False),
    ('cmp'   , argReg8     , argRegMem8  , False),
    ('cmp'   , argReg16    , argRegMem16 , False),
    ('cmp'   , reg('al')   , argImm8     , False),
    ('cmp'   , reg('ax')   , argImm16    , False),
    ('segds' , argNone     , argNone     , True),
    ('aas'   , argNone     , argNone     , False),
    ('inc'   , reg('ax')   , argNone     , False),
    ('inc'   , reg('cx')   , argNone     , False),
    ('inc'   , reg('dx')   , argNone     , False),
    ('inc'   , reg('bx')   , argNone     , False),
    ('inc'   , reg('sp')   , argNone     , False),
    ('inc'   , reg('bp')   , argNone     , False),
    ('inc'   , reg('si')   , argNone     , False),
    ('inc'   , reg('di')   , argNone     , False),
    ('dec'   , reg('ax')   , argNone     , False),
    ('dec'   , reg('cx')   , argNone     , False),
    ('dec'   , reg('dx')   , argNone     , False),
    ('dec'   , reg('bx')   , argNone     , False),
    ('dec'   , reg('sp')   , argNone     , False),
    ('dec'   , reg('bp')   , argNone     , False),
    ('dec'   , reg('si')   , argNone     , False),
    ('dec'   , reg('di')   , argNone     , False),
    ('push'  , reg('ax')   , argNone     , False),
    ('push'  , reg('cx')   , argNone     , False),
    ('push'  , reg('dx')   , argNone     , False),
    ('push'  , reg('bx')   , argNone     , False),
    ('push'  , reg('sp')   , argNone     , False),
    ('push'  , reg('bp')   , argNone     , False),
    ('push'  , reg('si')   , argNone     , False),
    ('push'  , reg('di')   , argNone     , False),
    ('pop'   , reg('ax')   , argNone     , False),
    ('pop'   , reg('cx')   , argNone     , False),
    ('pop'   , reg('dx')   , argNone     , False),
    ('pop'   , reg('bx')   , argNone     , False),
    ('pop'   , reg('sp')   , argNone     , False),
    ('pop'   , reg('bp')   , argNone     , False),
    ('pop'   , reg('si')   , argNone     , False),
    ('pop'   , reg('di')   , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    ('jo'    , argShort    , argNone     , False),
    ('jno'   , argShort    , argNone     , False),
    ('jb'    , argShort    , argNone     , False),
    ('jae'   , argShort    , argNone     , False),
    ('jz'    , argShort    , argNone     , False),
    ('jnz'   , argShort    , argNone     , False),
    ('jbe'   , argShort    , argNone     , False),
    ('ja'    , argShort    , argNone     , False),
    ('js'    , argShort    , argNone     , False),
    ('jns'   , argShort    , argNone     , False),
    ('jpe'   , argShort    , argNone     , False),
    ('jpo'   , argShort    , argNone     , False),
    ('jl'    , argShort    , argNone     , False),
    ('jge'   , argShort    , argNone     , False),
    ('jle'   , argShort    , argNone     , False),
    ('jg'    , argShort    , argNone     , False),
    (arop    , argRegMem8  , argImm8     , False),
    (arop    , argRegMem16 , argImm16    , False),
    (''      , argNone     , argNone     , False),
    (arop    , argRegMem16 , argSImm8    , False),
    ('test'  , argRegMem8  , argReg8     , False),
    ('test'  , argRegMem16 , argReg16    , False),
    ('xchg'  , argRegMem8  , argReg8     , False),
    ('xchg'  , argRegMem16 , argReg16    , False),
    ('mov'   , argRegMem8  , argReg8     , False),
    ('mov'   , argRegMem16 , argReg16    , False),
    ('mov'   , argReg8     , argRegMem8  , False),
    ('mov'   , argReg16    , argRegMem16 , False),
    ('mov'   , argRegMem16 , argSegReg   , False),
    ('lea'   , argReg16    , argMem8     , False),
    ('mov'   , argSegReg   , argRegMem16 , False),
    ('pop'   , argRegMem16 , argNone     , False),
    ('nop'   , argNone     , argNone     , False),
    ('xchg'  , reg('ax')   , reg('cx')   , False),
    ('xchg'  , reg('ax')   , reg('dx')   , False),
    ('xchg'  , reg('ax')   , reg('bx')   , False),
    ('xchg'  , reg('ax')   , reg('sp')   , False),
    ('xchg'  , reg('ax')   , reg('bp')   , False),
    ('xchg'  , reg('ax')   , reg('si')   , False),
    ('xchg'  , reg('ax')   , reg('di')   , False),
    ('cbw'   , argNone     , argNone     , False),
    ('cwd'   , argNone     , argNone     , False),
    ('call'  , argFar      , argNone     , False),
    ('wait'  , argNone     , argNone     , False),
    ('pushf' , argNone     , argNone     , False),
    ('popf'  , argNone     , argNone     , False),
    ('sahf'  , argNone     , argNone     , False),
    ('lahf'  , argNone     , argNone     , False),
    ('mov'   , reg('al')   , argMemOffs8 , False),
    ('mov'   , reg('ax')   , argMemOffs16, False),
    ('mov'   , argMemOffs8 , reg('al')   , False),
    ('mov'   , argMemOffs16, reg('ax')   , False),
    ('movsb' , argNone     , argNone     , False),
    ('movsw' , argNone     , argNone     , False),
    ('cmpsb' , argNone     , argNone     , False),
    ('cmpsw' , argNone     , argNone     , False),
    ('test'  , reg('al')   , argImm8     , False),
    ('test'  , reg('ax')   , argImm16    , False),
    ('stosb' , argNone     , argNone     , False),
    ('stosw' , argNone     , argNone     , False),
    ('lodsb' , argNone     , argNone     , False),
    ('lodsw' , argNone     , argNone     , False),
    ('scasb' , argNone     , argNone     , False),
    ('scasw' , argNone     , argNone     , False),
    ('mov'   , reg('al')   , argImm8     , False),
    ('mov'   , reg('cl')   , argImm8     , False),
    ('mov'   , reg('dl')   , argImm8     , False),
    ('mov'   , reg('bl')   , argImm8     , False),
    ('mov'   , reg('ah')   , argImm8     , False),
    ('mov'   , reg('ch')   , argImm8     , False),
    ('mov'   , reg('dh')   , argImm8     , False),
    ('mov'   , reg('bh')   , argImm8     , False),
    ('mov'   , reg('ax')   , argImm16    , False),
    ('mov'   , reg('cx')   , argImm16    , False),
    ('mov'   , reg('dx')   , argImm16    , False),
    ('mov'   , reg('bx')   , argImm16    , False),
    ('mov'   , reg('sp')   , argImm16    , False),
    ('mov'   , reg('bp')   , argImm16    , False),
    ('mov'   , reg('si')   , argImm16    , False),
    ('mov'   , reg('di')   , argImm16    , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    ('ret'  , argImm16    , argNone     , False),
    ('ret'  , argNone     , argNone     , False),
    ('les'   , argReg16    , argMem32    , False),
    ('lds'   , argReg16    , argMem32    , False),
    ('mov'   , argMem8     , argImm8     , False),
    ('mov'   , argMem16    , argImm16    , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    ('retf'  , argImm16    , argNone     , False),
    ('retf'  , argNone     , argNone     , False),
    ('int'   , const(3)    , argNone     , False),
    ('int'   , argImm8     , argNone     , False),
    ('into'  , argNone     , argNone     , False),
    ('iret'  , argNone     , argNone     , False),
    (shfop   , argRegMem8  , const(1)    , False),
    (shfop   , argRegMem16 , const(1)    , False),
    (shfop   , argRegMem8  , reg('cl')   , False),
    (shfop   , argRegMem16 , reg('cl')   , False),
    ('aam'   , argImm8     , argNone     , False),
    ('aad'   , argImm8     , argNone     , False),
    (''      , argNone     , argNone     , False),
    ('xlat'  , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    (''      , argNone     , argNone     , False),
    ('loopnz', argShort    , argNone     , False),
    ('loopz' , argShort    , argNone     , False),
    ('loop'  , argShort    , argNone     , False),
    ('jcxz'  , argShort    , argNone     , False),
    ('in'    , reg('al')   , argImm8     , False),
    ('in'    , reg('ax')   , argImm8     , False),
    ('out'   , argImm8     , reg('al')   , False),
    ('out'   , argImm8     , reg('ax')   , False),
    ('call'  , argNear     , argNone     , False),
    ('jmp'   , argNear     , argNone     , False),
    ('jmp'   , argFar      , argNone     , False),
    ('jmp'   , argShort    , argNone     , False),
    ('in'    , reg('al')   , reg('dx')   , False),
    ('in'    , reg('ax')   , reg('dx')   , False),
    ('out'   , reg('dx')   , reg('al')   , False),
    ('out'   , reg('dx')   , reg('ax')   , False),
    ('lock'  , argNone     , argNone     , True),
    (''      , argNone     , argNone     , False),
    ('repne' , argNone     , argNone     , True),
    ('rep'   , argNone     , argNone     , True),
    ('hlt'   , argNone     , argNone     , False),
    ('cmc'   , argNone     , argNone     , False),
    (grp1    , argRegMem8  , argNone     , False),
    (grp1    , argRegMem16 , argNone     , False),
    ('clc'   , argNone     , argNone     , False),
    ('stc'   , argNone     , argNone     , False),
    ('cli'   , argNone     , argNone     , False),
    ('sti'   , argNone     , argNone     , False),
    ('cld'   , argNone     , argNone     , False),
    ('std'   , argNone     , argNone     , False),
    (grp2    , argRegMem8  , argNone     , False),
    (grp3    , argRegMem16 , argNone     , False),
)
    
    
    
    